### PR TITLE
Adds tvos deployment target

### PR DESCRIPTION
**Pull request by aixinyunchou**

### CODE REVIEW

**Comment by danshevluk** [comment]
You have to rebase `master` brunch to be able to merge this PR without conflicts.

**Comment by mrecke01** [comment]
Can TVOS please be added to pod spec? I want to use cocoa pods on a TVOS app in combination with SwiftSocket

**Comment by danshevluk** [comment]
Yes, we can add it but I guess there is no tvOS target in our project. You add it and create a new PR to do that, or contribute to this one.

**Comment by mrecke01** [comment]
Don’t know how to do that? normally I just add all the libraries in the pods framework and they get installed automatically…independent if they are IOS or TVOS.
Before I just copied the files into the project and that worked…but cocoa pods are much easier because you can update all libraries with one command.

Would you be able to help?

**Comment by danshevluk** [comment]
Yeah, ok. I'll make it today 🎉  🎉

**Comment by danshevluk** [comment]
Moved to #50

**Pull request closed without merging**
